server:
  port: 4000
  servlet:
    context-path: /api/v1

spring:
  application:
    name: user-service
  datasource:
    url: ${url}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${username}
    password: ${password}
    hikari:
      maximum-pool-size: 50
      minimum-idle: 5
      max-lifetime: 1800000 #30min
      idle-timeout: 600000 #10min

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  security:
    oauth2:
      client:
        registration:
          auth-service:
            client-id: user-service-client
            client-secret: user-service-secret
            authorization-grant-type: authorization_code
            scope: read,write,openid,profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          auth-service:
            authorization-uri: http://localhost:3000/api/v1/oauth2/authorize
            token-uri: http://localhost:3000/api/v1/oauth2/token
            jwk-set-uri: http://localhost:3000/api/v1/oauth2/jwks
            user-info-uri: http://localhost:3000/api/v1/userinfo
            user-name-attribute: sub
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:3000/api/v1/oauth2/jwks

logging:
  level:
    org.hibernate.type.descriptor.sql: debug
    com.service.user: debug
    org.springframework.security: debug