server:
  port: 4000
  servlet:
    context-path: /api

spring:
  application:
    name: user-service
  datasource:
    url: ${url}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${username}
    password: ${password}
    hikari:
      maximum-pool-size: 50
      minimum-idle: 5
      max-lifetime: 1800000 #30min
      idle-timeout: 600000 #10min

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

# JWT 설정 추가
jwt:
  secret: ${JWT_SECRET:your_jwt_secret_key_should_be_at_least_32_bytes_long_for_hs512}
  token-validity-in-seconds: 3600
  refresh-token-validity-in-seconds: 86400

logging:
  level:
    org.hibernate.type.descriptor.sql: debug
    com.service.user: debug
    org.springframework.security: debug