spring:
  application:
    name: gate-way
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: debug  # query? ?? ?? ?? ????? ??? ? ?? ?????. TRACE Log? ?? ?????.
file:
  dir: ${fileDir}