server:
  port: 3000
  servlet:
    context-path: /api/v1

spring:
  application:
    name: auth-service
  datasource:
    url: ${url}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${username}
    password: ${password}
    hikari:
      maximum-pool-size: 50
      minimum-idle: 5
      max-lifetime: 1800000 #30min
      idle-timeout: 600000 #10min

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

# OAuth 2.0 ?? ??
oauth2:
  token:
    access-token-validity: 3600  # 1?? (? ??)
    refresh-token-validity: 86400  # 24?? (? ??)

# ? ?? ??
key-management:
  rotation:
    enabled: true
    cron: "0 0 0 1 */3 *"

logging:
  level:
    org.hibernate.type.descriptor.sql: debug
    com.service.auth: debug